server:
  port: 9090

spring:
  profiles:
    active: dev

country: us
person:
  name: Alexander
  hometown: shaoxing
  birthday: 1992/5/14


  maps: {k1: shanghai, k2: hangzhou}
  hobbies:
    - swim
    - bike

  dog:
    name: spike
    age: ${random.int}
---
server:
  port: 8081
spring:
  profiles: dev

person:
  name: Horatio
  hometown: shaoxing
  birthday: 1992/5/14


  maps: {k1: beijing, k2: hangzhou}
  hobbies:
    - swim
    - book

  dog:
    name: spike
    age: ${random.int}

---
server:
  port: 8082
spring:
  profile: prod